env: "local"

server:
  port: "8080"

database:
  host: "localhost"
  port: "5432"
  user: "yourusername"
  password: "yourpassword"
  name: "emergency_notification_system"

telegram:
  bot_token: "your_telegram_bot_token"
